name: Build

env:
  CARGO_TERM_COLOR: always

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsoup-3.0-dev libwebkit2gtk-4.1-dev libgtk-3-dev \
            webkit2gtk-4.0 javascriptcoregtk-4.1 libappindicator3-dev \
            librsvg2-dev patchelf libdbus-1-dev \
            pkg-config \

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Upload amd64 deb
        uses: actions/upload-artifact@v4
        with:
          name: Ark-Rate-Desktop_amd64.deb.zip
          path: ./src-tauri/target/release/bundle/deb/Ark-Rate-Desktop*amd64*.deb

      - name: Upload x86_64 rpm
        uses: actions/upload-artifact@v4
        with:
          name: Ark-Rate-Desktop_x86_64.rpm.zip
          path: ./src-tauri/target/release/bundle/rpm/Ark-Rate-Desktop*x86_64*.rpm

      - name: Upload amd64 AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Ark-Rate-Desktop_amd64.AppImage.zip
          path: ./src-tauri/target/release/bundle/appimage/Ark-Rate-Desktop*amd64*.AppImage

  macos:
    runs-on: macos-latest
    args: '--target universal-apple-darwin'

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.x'

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: Ark-Rate-Desktop.app.zip
          path: ./src-tauri/target/release/bundle/macos/Ark-Rate-Desktop*.app

      - name: Upload aarch64 dmg
        uses: actions/upload-artifact@v4
        with:
          name: Ark-Rate-Desktop_aarch64.dmg.zip
          path: ./src-tauri/target/release/bundle/dmg/Ark-Rate-Desktop*aarch64*.dmg

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.x'

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Upload x64 msi
        uses: actions/upload-artifact@v4
        with:
          name: Ark-Rate-Desktop_x64.msi.zip
          path: ./src-tauri/target/release/bundle/msi/Ark-Rate-Desktop*x64*.msi

      - name: Upload x64 exe
        uses: actions/upload-artifact@v4
        with:
          name: Ark-Rate-Desktop_x64.exe.zip
          path: ./src-tauri/target/release/bundle/nsis/Ark-Rate-Desktop*x64*.exe
