name: Build

env:
  CARGO_TERM_COLOR: always

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsoup-3.0-dev libwebkit2gtk-4.1-dev libgtk-3-dev \
            webkit2gtk-4.0 javascriptcoregtk-4.1 libappindicator3-dev \
            librsvg2-dev patchelf libdbus-1-dev \
            pkg-config \

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Upload AppImage
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Ark-Rate-Desktop.AppImage
          path: ./src-tauri/target/release/bundle/appimage/Ark-Rate-Desktop*.AppImage

      - name: Upload deb
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Ark-Rate-Desktop.deb
          path: ./src-tauri/target/release/bundle/deb/Ark-Rate-Desktop*.deb

      - name: Upload rpm
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Ark-Rate-Desktop.rpm
          path: ./src-tauri/target/release/bundle/rpm/Ark-Rate-Desktop*.rpm

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.x'

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Upload app
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Ark-Rate-Desktop.app
          path: ./src-tauri/target/release/bundle/macos/Ark-Rate-Desktop*.app

      - name: Upload dmg
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Ark-Rate-Desktop.dmg
          path: ./src-tauri/target/release/bundle/dmg/Ark-Rate-Desktop*.dmg

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.x'

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build
