name: Release the app

env:
  CARGO_TERM_COLOR: always

on:
  push:
    tags:
      - '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsoup-3.0-dev libwebkit2gtk-4.1-dev libgtk-3-dev \
            webkit2gtk-4.0 javascriptcoregtk-4.1 libappindicator3-dev \
            librsvg2-dev patchelf libdbus-1-dev \
            pkg-config \

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Release amd64 deb
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src-tauri/target/release/bundle/deb/Ark-Rate-Desktop*amd64*.deb
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release x86_64 rpm
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src-tauri/target/release/bundle/rpm/Ark-Rate-Desktop*x86_64*.rpm
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release amd64 AppImage
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src-tauri/target/release/bundle/appimage/Ark-Rate-Desktop*amd64*.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.x'

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Release app
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src-tauri/target/release/bundle/macos/Ark-Rate-Desktop*.app
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release aarch64 dmg
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src-tauri/target/release/bundle/dmg/Ark-Rate-Desktop*aarch64*.dmg
          token: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.x'

      - name: Fetch Node.js Dependencies
        run: yarn

      - name: Build Release version
        run: yarn tauri build

      - name: Release x64 msi
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src-tauri/target/release/bundle/msi/Ark-Rate-Desktop*x64*.msi
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release x64 exe
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src-tauri/target/release/bundle/nsis/Ark-Rate-Desktop*x64*.exe
          token: ${{ secrets.GITHUB_TOKEN }}
